# Please access https://squidfunk.github.io/mkdocs-material for more details.
site_name: BioVisReport
site_description: 'For Scientifically Interactive Report'
site_author: 'Jingcheng Yang'
announce: 'BioVisReport Team'
announce_text: 'biovis-report v0.5.6 is released.'
docs_dir: source
repo_name: 'biovis-report'
repo_url: 'https://github.com/biovis-report'
edit_uri: https://github.com/biovis-report/biovis-report/edit/master/docs/source
markdown_extensions:
  # - mkautodoc
  - meta
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/bootstrap-grid.min.css
plugins:
  - search
  - git-revision-date
extra:
  homepage: https://biovis-report.github.io
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/biovis-report
      name: BioVisReport
  generator: false
copyright: Copyright &copy; 2016 - 2022 BioVisReport Team
theme:
  custom_dir: source/assets/overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - navigation.expand
  icon:
      repo: fontawesome/brands/github
  favicon: assets/images/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode
  name: 'material'

# Table of contents
nav:
  - 'Home': index.md
  - 'Getting Started':
    - 'Introduction': docs/getting-started.md
    - 'Installation': docs/installation.md
    - 'Launch the Example': docs/launch-example.md
    - 'Write Your Report': docs/write-your-report.md
    - 'Publish Your Report': docs/publish-your-report.md
    # - 'For Mac Users': docs/installation/mac.md
    # - 'For Window Users': docs/installation/windows.md
    # - 'For Linux Users': docs/installation/linux.md
  - 'Design': docs/biovis-report.md
  - 'Plugins':
    - 'Introduction': docs/plugins.md
    - 'JavaScript-Based Plugins':
      - 'datatable-js': docs/plugins/js-based/datatable-js.md
      - 'pivot-table-js': docs/plugins/js-based/pivot-table-js.md
      - 'pie-chart-js': docs/plugins/js-based/pie-chart-js.md
      - 'tabulator-js': docs/plugins/js-based/tabulator-js.md
    - 'R-Based Plugins':
      - 'barplot-r': docs/plugins/r-based/barplot-r.md
      - 'boxplot-r': docs/plugins/r-based/boxplot-r.md
      - 'corrplot-r': docs/plugins/r-based/corrplot-r.md
      - 'density-plot-r': docs/plugins/r-based/density-plot-r.md
      - 'grouped-boxplot-r': docs/plugins/r-based/grouped-boxplot-r.md
      # - 'heatmap-r': docs/plugins/r-based/heatmap-r.md
      - 'heatmap-d3-r': docs/plugins/r-based/heatmap-d3-r.md
      - 'lineplot-r': docs/plugins/r-based/lineplot-r.md
      # - 'lollipop-plot-r': docs/plugins/r-based/lollipop-plot-r.md
      - 'rocket-plot-r': docs/plugins/r-based/rocket-plot-r.md
      - 'scatter-plot-r': docs/plugins/r-based/scatter-plot-r.md
      - 'stack-barplot-r': docs/plugins/r-based/stack-barplot-r.md
      - 'upset-r': docs/plugins/r-based/upset-r.md
      - 'violin-plot-r': docs/plugins/r-based/violin-plot-r.md
    - 'Python-Based Plugins':
      - 'multiqc-py': docs/plugins/py-based/multiqc-py.md
  - 'Examples': 
      - 'Introduction': docs/examples.md
  - 'FAQs': docs/faqs.md
  - 'About': docs/about.md
