# Please access https://squidfunk.github.io/mkdocs-material for more details.
site_name: BioVisReport
site_description: 'For Scientifically Interactive Report'
site_author: 'Jingcheng Yang'
announce: 'BioVisReport Team'
announce_text: ''
docs_dir: source
repo_name: 'biovis-report'
repo_url: 'https://github.com/biovis-report'
edit_uri: https://github.com/biovis-report/biovis-report/edit/master/docs/source
markdown_extensions:
  # - mkautodoc
  - meta
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - search
  - git-revision-date
extra:
  homepage: https://biovis-report.github.io
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/biovis-report
      name: BioVisReport
  generator: false
copyright: Copyright &copy; 2016 - 2022 Jingcheng Yang
theme:
  custom_dir: source/assets/overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
  icon:
      repo: fontawesome/brands/github
  favicon: assets/images/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode
  name: 'material'

# Table of contents
nav:
  - Home: index.md
