# {% set data = load_setup_py_data() %}
{% set version = '0.3.8.dev0' %}
{% set url = 'http://choppy.3steps.cn/go-choppy/choppy-report' %}
{% set description = 'Choppy-report is a tool for generating a scientifically interactive report.' %}

package:
  name: choppy-report
  version: {{ version }}


source:
  - path: ../


build:
  include_recipe: True
  entry_points:
    - choppy-report = report.__main__:main


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - click
    - Jinja2
    - livereload
    - lunr
    - nltk
    - singledispatch
    - Markdown
    - PyYAML
    - tornado
    - beautifulsoup4
    - psutil
    - coloredlogs
    - argcomplete
    - toml
    - pymdown-extensions

test:
  commands:
    - choppy-report -h

about:
  home: {{ url }}
  license: AGPL 3.0
  license_file: LICENSE
  license_family: GNU

  summary: {{ description }}
  description: 'Choppy-report is a fast, simple and downright gorgeous interactive report generator that's geared towards building scientific report. Report source files are written in Markdown, and configured with a single TOML configuration file.'
  doc_url: http://docs.3steps.cn
  dev_url: {{ url }}