{% set data = load_setup_py_data() %}
# {% set version = '0.4.00' %}
# {% set url = 'https://github.com/biovis-report/biovis-report' %}
# {% set description = 'BioVisReport is a tool for generating a scientifically interactive report.' %}

package:
  name: biovis-report
  version: {{ data.version }}


source:
  - path: ../


build:
  include_recipe: True
  entry_points:
    - biovis-report = biovis_report.__main__:main


requirements:
  build:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - Jinja2 ~=2.11
    - markupsafe ~=2.0.1
    - PyYAML ~=6.0
    - toml ~=0.10
    - verboselogs ~=1.7
    - psutil ~=5.9
    - coloredlogs ~=15.0
    - argcomplete ~=2.0
    - jsonschema ~=4.5
    - pyparsing ~=3.0
    - requests ~=2.27
    - Markdown ~=3.3
    - sqlalchemy ~=1.4
    - mkdocs ~=1.2
    - mkdocs-material ~=8.2
    - mkdocs-material-extensions ~=1.0
    - pygments ~=2.12
    - pymdown-extensions ~=9.4

test:
  commands:
    - biovis-report -h
  imports:
    - biovis_media_extension

about:
  home: {{ data.url }}
  license: MIT
  license_file: LICENSE
  license_family: MIT

  summary: {{ data.description }}
  description: Biovis-report is a fast, simple and downright gorgeous interactive report generator that's geared towards building scientific report. Report source files are written in Markdown, and configured with a single TOML configuration file.
  doc_url: https://biovis.report
  dev_url: {{ data.url }}