{% set data = load_setup_py_data() %}
# {% set version = '0.4.00' %}
# {% set url = 'https://github.com/biovis-report/biovis-report-core' %}
# {% set description = 'BioVisReport is a tool for generating a scientifically interactive report.' %}

package:
  name: biovis-report
  version: {{ data.version }}


source:
  - path: ../


build:
  include_recipe: True
  entry_points:
    - biovis-report = biovis_report.__main__:main


requirements:
  build:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - click
    - Jinja2
    - PyYAML
    - toml
    - verboselogs
    - psutil
    - coloredlogs
    - argcomplete
    - jsonschema
    - mkdocs ~=1.2
    - plotly~=3.6.1
    - bokeh~=2.4
    - Markdown~=3.0
    - pyparsing~=2.3
    - requests~=2.21
    - multiqc~=1.10
    - sqlalchemy~=1.4

test:
  commands:
    - biovis-report -h

about:
  home: {{ data.url }}
  license: AGPL 3.0
  license_file: LICENSE
  license_family: AGPL

  summary: {{ data.description }}
  description: Biovis-report is a fast, simple and downright gorgeous interactive report generator that's geared towards building scientific report. Report source files are written in Markdown, and configured with a single TOML configuration file.
  doc_url: https://biovis-report.github.io
  dev_url: {{ data.url }}