# {% set data = load_setup_py_data() %}
{% set version = '1.1.dev0' %}
{% set url = 'http://choppy.3steps.cn' %}
{% set description = 'Project documentation with Markdown.' %}

package:
  name: mkdocs
  version: {{ version }}


source:
  - path: ../


build:
  include_recipe: True
  entry_points:
    - mkdocs = mkdocs.__main__:cli


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - click
    - Jinja2
    - livereload
    - lunr
    - nltk
    - singledispatch
    - Markdown
    - PyYAML
    - tornado
    - beautifulsoup4

    # meta-package installs futures for 2.7 but not for 3.x
    # needed in order to be able to build no-arch conda packages
    - futures-compat

test:
  commands:
    - mkdocs -h

about:
  home: {{ url }}
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD

  summary: {{ description }}
  description: 'Project documentation with Markdown.'
  doc_url: http://docs.3steps.cn
  dev_url: {{ url }}