name: release-package
on:
  push:
    tags:
      - v*
    branches:
      - master    

jobs:
  release-package:
    name: Run (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Package & upload
        shell: bash -l {0}
        run: conda build ./conda.recipe --token ${{ secrets.ANACONDA_TOKEN }}