name: release-package
on:
  push:
    tags:
      - v*
    branches:
      - master    

jobs:
  release_package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        pythonVersion: [3.7, 3.8, 3.9, 3.10]
        # exclude:
        #   - os: macos-latest
        #     pythonVersion: 3.8
        #   - os: windows-latest
        #     pythonVersion: 3.6
    steps:
    - uses: actions/checkout@v2
    - name: Anaconda-Action
      id: step1
      uses: fdiblen/anaconda-action@0.1.7
      with:
        envFileName: './conda.recipe/meta.yml'
        publish: true
        channels: conda-forge,bioconda
        publishChannel: biovis-report
        anacondaToken: ${{ secrets.ANACONDA_TOKEN }}